<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "assalat"
 *
 * Auto generated by Extension Builder 2018-03-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Assalat',
    'description' => 'Display islamic praying times for cities all over ther world. (Salat, Salah asr, Namaz vakitleri, Gebetszeiten)',
    'category' => 'plugin',
    'author' => 'Muhammed Ali Alat',
    'author_email' => 'muhammedali@alat.de',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
